module.exports = {
  SYSTEM_DEFAULT: "System Default",
  CZECH: "Czech",
  SPANISH: "Spanish",
  ITALIAN: "Italian",
  GERMAN: "German",
  ENGLISH: "English",
  SWEDISH: "Swedish",
  FINNISH: "Finnish",
  VIETNAMESE: "Vietnamese",
  RUSSIAN: "Russian",
  UKRAINIAN: "Ukrainian",
  SLOVAK: "Slovak",
  PORTUGUESE_BR: "Portuguese_br",
  INDONESIAN: "Indonesia",
  JAPANESE: "Japanese",
  TURKISH: "Turkish",
  CATALAN: "Catalan",
  POLISH: "Polish",
  CHINESE: "Chinese",
  GREEK: "Greek",
  NORWEGIAN: "Norwegian",
  BULGARIAN: "Bulgarian",
  FRENCH: "French",
  PORTUGUESE: "Portuguese",
  PERSIAN: "Persian",
  ROMANIAN: "Romanian",
  DUTCH: "Dutch",
};
